FROM charliehuang09095/photonvision_dependancies AS builder

WORKDIR /
COPY photonvision photonvision
WORKDIR /photonvision
RUN rm -r .gradle
RUN find -name "*.jar"
CMD ["java", "-jar", "./photon-server/build/libs/photonvision-dev-Unknown-linuxarm64.jar"]
